'use strict';
const $=s=>document.querySelector(s),canvas=$('#map'),ctx=canvas.getContext('2d');
const banks=new Map(),tracks=new Map();let current=null,bank=null,mode='inspect',history=[],cache=new Map(),dirty=false,selected=null;
const status=s=>$('#status').textContent=s;
function script(src){const s=document.createElement('script');s.src=src;s.onerror=()=>status('No se pudo cargar '+src);document.head.append(s)}
function bytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function words(s){const b=bytes(s),v=new DataView(b.buffer);return Uint16Array.from({length:b.length/2},(_,i)=>v.getUint16(i*2,true))}
window.loadBank=data=>{data.pix=bytes(data.pixels);delete data.pixels;data.files=new Set(data.files);banks.set(data.world,data);maybeReady()};
window.loadTrack=data=>{data.original=words(data.words);data.refs=words(data.refs);delete data.words;tracks.set(data.track,data);maybeReady()};
function maybeReady(){const id=Number($('#track').value),row=CATALOG.tracks.find(t=>t.id===id);if(!row||!tracks.has(id)||!banks.has(row.world))return;const source=tracks.get(id);current={...source,map:source.original.slice()};bank=banks.get(row.world);cache=new Map();history=[];dirty=false;selected=null;$('#tmxlink').href=`mapas/${String(id).padStart(2,'0')}/mapa_editable.tmx`;$('#pnglink').href=`mapas/${String(id).padStart(2,'0')}/circuito.png`;$('#atlaslink').href=`bancos/${String(row.world).padStart(2,'0')}/ATLAS_NUMERADO.png`;draw();brush();status(`Circuito ${id} · ${row.world_name} · 3072×920`)}
function choose(){const id=Number($('#track').value),row=CATALOG.tracks.find(t=>t.id===id);current=null;status('Cargando circuito '+id+'…');if(!banks.has(row.world))script(`bancos/${String(row.world).padStart(2,'0')}/datos.js`);if(!tracks.has(id))script(`mapas/${String(id).padStart(2,'0')}/datos.js`);maybeReady()}
function filter(){const world=$('#world').value,list=CATALOG.tracks.filter(t=>world==='all'||t.world===Number(world));$('#track').replaceChildren(...list.map(t=>new Option(`${String(t.id).padStart(2,'0')} · ${t.world_name}`,t.id)));$('#gallery').replaceChildren(...list.map(t=>{const b=document.createElement('button'),im=document.createElement('img');im.src=`${t.path}/miniatura.png`;im.loading='lazy';b.append(im,document.createTextNode(String(t.id).padStart(2,'0')));b.onclick=()=>{if(!discard())return;$('#track').value=String(t.id);choose()};return b}));choose()}
function discard(){return !dirty||confirm('Hay cambios sin guardar. ¿Cambiar de circuito y descartarlos?')}
function tile(word){if(cache.has(word))return cache.get(word);const c=document.createElement('canvas');c.width=c.height=8;const x=c.getContext('2d'),im=x.createImageData(8,8),t=word&2047,p=word>>13&3;for(let y=0;y<8;y++)for(let a=0;a<8;a++){const xx=word&2048?7-a:a,yy=word&4096?7-y:y,index=bank.pix[t*64+yy*8+xx],color=bank.colors[p*16+index],off=(y*8+a)*4;im.data.set([...color,index?255:0],off)}x.putImageData(im,0,0);cache.set(word,c);return c}
function visible(){return $('#layer').value==='both'?[1,0]:[Number($('#layer').value)]}
function cell(i){const x=i%384*8,y=Math.floor(i/384)*8;ctx.clearRect(x,y,8,8);ctx.fillStyle='#000';ctx.fillRect(x,y,8,8);for(const priority of [0,1])for(const p of visible()){const w=current.map[p*44160+i];if(w>>>15===priority)ctx.drawImage(tile(w),x,y)}}
function draw(){if(!current)return;ctx.clearRect(0,0,3072,920);ctx.fillStyle='#000';ctx.fillRect(0,0,3072,920);for(const priority of [0,1])for(const p of visible())for(let i=0;i<44160;i++){const w=current.map[p*44160+i];if(w>>>15===priority)ctx.drawImage(tile(w),i%384*8,Math.floor(i/384)*8)}if($('#grid').checked){ctx.strokeStyle='#ffffff38';ctx.lineWidth=.5;ctx.beginPath();for(let x=0;x<3072;x+=8){ctx.moveTo(x,0);ctx.lineTo(x,920)}for(let y=0;y<920;y+=8){ctx.moveTo(0,y);ctx.lineTo(3072,y)}ctx.stroke()}if(selected!==null&&mode==='inspect'){ctx.strokeStyle='#00efff';ctx.lineWidth=1;for(const p of visible())for(let i=0;i<44160;i++)if((current.map[p*44160+i]&2047)===selected)ctx.strokeRect(i%384*8+.5,Math.floor(i/384)*8+.5,7,7)}const z=Number($('#zoom').value);canvas.style.width=3072*z+'px';canvas.style.height=920*z+'px'}
function brushWord(){return (Number($('#tile').value)&2047)|(Number($('#palette').value)<<13)|($('#fx').checked?2048:0)|($('#fy').checked?4096:0)|($('#priority').checked?32768:0)}
function brush(){if(!bank)return;const w=brushWord(),c=$('#preview').getContext('2d');c.clearRect(0,0,8,8);c.drawImage(tile(w),0,0);const t=w&2047,p=w>>13&3,f=bank.files.has(t+'_'+p);$('#tilelink').hidden=!f;$('#tilelink').href=`bancos/${String(current.world).padStart(2,'0')}/tiles/paleta_${p}/tile_${String(t).padStart(4,'0')}.png`}
function coordinates(e){const b=canvas.getBoundingClientRect();return [Math.min(3071,Math.max(0,Math.floor((e.clientX-b.left)/b.width*3072))),Math.min(919,Math.max(0,Math.floor((e.clientY-b.top)/b.height*920)))]}
let dragging=false,last=-1;
function action(e){if(!current)return;const [x,y]=coordinates(e),i=Math.floor(y/8)*384+Math.floor(x/8);if(mode==='paint'){const p=Number($('#target').value),at=p*44160+i,w=brushWord();if(at===last||current.map[at]===w)return;last=at;history.push([at,current.map[at]]);current.map[at]=w;dirty=true;selected=null;cell(i);status('Montaje editado. Guarda tu proyecto JSON.');return}let best=null;for(const pri of [0,1])for(const p of visible()){const w=current.map[p*44160+i],xx=w&2048?7-x%8:x%8,yy=w&4096?7-y%8:y%8;if(w>>>15===pri&&bank.pix[(w&2047)*64+yy*8+xx])best={p,w}}best=best||{p:visible().at(-1),w:current.map[visible().at(-1)*44160+i]};const w=best.w,t=w&2047;selected=t;$('#tile').value=t;$('#palette').value=w>>13&3;$('#fx').checked=!!(w&2048);$('#fy').checked=!!(w&4096);$('#priority').checked=!!(w&32768);$('#target').value=best.p;const count=Array.from(current.map).filter(v=>(v&2047)===t).length;$('#info').textContent=`Tile ${t} · paleta ${w>>13&3}\nCapa ${best.p}\nPosición (${Math.floor(x/8)}, ${Math.floor(y/8)})\nApariciones: ${count}\n${mode==='inspect'?'Seleccionado como pincel.':''}`;brush();draw()}
canvas.onpointerdown=e=>{dragging=true;last=-1;canvas.setPointerCapture(e.pointerId);action(e)};canvas.onpointermove=e=>{if(dragging&&mode==='paint')action(e)};canvas.onpointerup=()=>{dragging=false;last=-1};
$('#inspect').onclick=()=>{mode='inspect';status('Selecciona un tile para ver sus usos');draw()};$('#paint').onclick=()=>{mode='paint';selected=null;status('Pinta sobre la capa de destino elegida');draw()};
$('#undo').onclick=()=>{if(!current||!history.length)return;const [at,w]=history.pop();current.map[at]=w;dirty=true;draw();status('Cambio deshecho')};
for(const s of ['#tile','#palette','#fx','#fy','#priority'])$(s).onchange=brush;
for(const s of ['#zoom','#layer','#grid'])$(s).onchange=draw;
$('#save').onclick=()=>{if(!current)return;const obj={format:'rnr-track-edit-v1',track:current.track,world:current.world,width:384,height:115,words:Array.from(current.map)};const u=URL.createObjectURL(new Blob([JSON.stringify(obj)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=`circuito_${String(current.track).padStart(2,'0')}_editado.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);dirty=false;status('Edición guardada en JSON; la ROM no se ha modificado')};
$('#open').onclick=()=>$('#file').click();$('#file').onchange=async()=>{try{const file=$('#file').files[0];if(!file)return;const d=JSON.parse(await file.text());if(!current||d.format!=='rnr-track-edit-v1'||d.track!==current.track||d.world!==current.world||d.width!==384||d.height!==115||!Array.isArray(d.words)||d.words.length!==88320||d.words.some(x=>!Number.isInteger(x)||x<0||x>65535))throw Error('Abre primero el circuito correspondiente. El archivo debe ser una edición JSON válida.');current.map=Uint16Array.from(d.words);history=[];dirty=false;selected=null;draw();status('Edición restaurada: circuito '+d.track)}catch(e){status(e.message)}finally{$('#file').value=''}};
for(const b of CATALOG.banks)$('#world').append(new Option(b.name,b.id));$('#world').onchange=()=>{if(discard())filter()};$('#track').onchange=()=>{if(discard())choose();else if(current)$('#track').value=current.track};filter();
